### ISSUE TITLE
Cannot generate sashimi plot on uploaded RNAseq data

### ISSUE THREAD

**Issue by ChiaraF32** [broadinstitute/tgg-viewer#38]
HI, 

I uploaded a RNAseq bam file into tgg viewer but I cannot visualise splice junctions using sashimi plots. 

I can see the splice junctions for the control datasets but not my personal data. 

Is there a feature for this or is it not available?

Thanks!

**Comment by bw2** [comment]
Hi @ChiaraF32 , 
tgg-viewer sashimi plots are drawn from a custom .bed format rather than from bam files. (This makes it much more efficient - you only need to load a single line from a text file for each junction instead of a whole bunch of reads). 

You will need to generate a bed file in this format for each of your samples. The easiest way to do this is to first get a splice junction table from STAR (the *.SJ.out.tab file it generates) and then convert it to .bed.gz & .tbi using the script in 
https://github.com/broadinstitute/tgg-viewer/tree/master/sample_preprocessing/splice_junction_track

**Comment by bw2** [comment]
Once you have the .bed.gz + .tbi file(s), you need to upload them to a google bucket and then give the .bed files'  gs:// path to tgg-viewer.

**Comment by ChiaraF32** [comment]
Thanks @bw2 for your help, I now have it working
